# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: fff2c40f19149e91d4fa49686bfebf120b20b57798588bcbd82616fef3d0889840e09222127c4649ef55d19e473cf05e1ec056f7deb1779cf54f18326231cde8

test:
  secret_key_base: adf811d81bf3ba3e68ca793581f2221251bc7a4b38d077316a49bbd84b8bb7a2b490e063f52b74a36f6a10581feaf1c6b1920977cb8cf1babbb55cd5eb8e0299

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
